#!/bin/bash

#
# Setup the dotfiles by running `stow` on relevant directories.
#

if ! which stow >/dev/null ; then
	echo "[error] requires [GNU Stow](https://www.gnu.org/software/stow/)"
	exit 1
fi

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
pushd $script_dir/.. >/dev/null

# need to stow this first to reset .stow-global-ignore
stow -R stow

for dd in $(ls); do
	# stow everything except stow and this script directory
	if [ -d $dd -a "$dd" != "script" -a "$dd" != "stow" ]; then
		echo "Stowing ... $dd"
		stow -R $dd
	fi
done

popd >/dev/null

